"""
hawkes.py - Univariate Hawkes process: simulation and MLE fitting.

Theory
------
A Hawkes process is a self-exciting point process where each event temporarily
raises the probability of future events ("order clustering").

Intensity at time t:

    lambda(t) = mu + sum_{t_i < t} alpha * exp(-beta * (t - t_i))

    mu    - baseline (exogenous) intensity
    alpha - excitation: how much each trade raises future intensity
    beta  - decay rate: how quickly that excitement fades

Stationarity requires alpha < beta.

Branching ratio  rho = alpha / beta
    Fraction of events generated by prior events (vs. exogenous news).
    Typical liquid markets: rho ~ 0.5-0.9.
    If rho spikes toward 1.0 -> the market is running hot; pure feedback loop.

Log-likelihood (used for MLE fitting)
--------------------------------------
    LL = sum_i log(mu + alpha * R_i)  -  mu*T  -  (alpha/beta) * sum_i [1 - exp(-beta*(T - t_i))]

where R_i = exp(-beta * (t_i - t_{i-1})) * (1 + R_{i-1})  is the O(n) recursive sum.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import minimize


# ── parameter / result types ──────────────────────────────────────────────────

@dataclass(frozen=True)
class HawkesParams:
    mu: float       # baseline intensity  (events per time unit)
    alpha: float    # excitation magnitude
    beta: float     # decay rate

    @property
    def branching_ratio(self) -> float:
        """Fraction of events spawned by prior events (not exogenous news)."""
        return self.alpha / self.beta

    @property
    def stationary(self) -> bool:
        """Process is stationary iff alpha < beta."""
        return self.alpha < self.beta

    @property
    def avg_intensity(self) -> float:
        """Unconditional mean intensity (events per time unit)."""
        if not self.stationary:
            return float("inf")
        return self.mu / (1.0 - self.branching_ratio)

    def intensity_at(self, t: float, event_times: np.ndarray) -> float:
        """lambda(t) given all past events."""
        past = event_times[event_times < t]
        return self.mu + self.alpha * float(np.sum(np.exp(-self.beta * (t - past))))


@dataclass(frozen=True)
class HawkesFitResult:
    params: HawkesParams
    log_likelihood: float
    n_events: int
    T: float
    converged: bool

    def summary(self) -> str:
        rho = self.params.branching_ratio
        lines = [
            f"  mu (baseline intensity)  : {self.params.mu:.4f} events/unit",
            f"  alpha (excitation)       : {self.params.alpha:.4f}",
            f"  beta  (decay)            : {self.params.beta:.4f}",
            f"  branching ratio (rho)    : {rho:.4f}",
            f"  avg intensity            : {self.params.avg_intensity:.4f} events/unit",
            f"  log-likelihood           : {self.log_likelihood:.2f}",
            f"  n events                 : {self.n_events:,}",
            f"  interpretation           : {self._interpret()}",
        ]
        return "\n".join(lines)

    def _interpret(self) -> str:
        rho = self.params.branching_ratio
        if rho > 0.85:
            return "Hot market - pure feedback loop, widen spread aggressively"
        if rho > 0.70:
            return "Active clustering - monitor, consider widening spread"
        if rho > 0.50:
            return "Moderate clustering - normal for a liquid market"
        return "Low clustering - mostly exogenous order flow"


# ── log-likelihood ─────────────────────────────────────────────────────────────

def hawkes_log_likelihood(
    params: tuple[float, float, float],
    event_times: np.ndarray,
    T: float,
) -> float:
    """
    Negative log-likelihood for a univariate Hawkes process.

    Recursive O(n) computation of the compensator and intensity terms.
    Returns +inf for invalid parameter combinations (enforces constraints).
    """
    mu, alpha, beta = params

    if mu <= 0 or alpha <= 0 or beta <= 0 or alpha >= beta:
        return 1e10

    n = len(event_times)
    if n == 0:
        return mu * T  # just the compensator

    # ── O(n) recursive R ──────────────────────────────────────────────────────
    R = np.zeros(n)
    for i in range(1, n):
        dt = event_times[i] - event_times[i - 1]
        R[i] = np.exp(-beta * dt) * (1.0 + R[i - 1])

    # ── log-intensity terms ───────────────────────────────────────────────────
    log_terms = np.log(mu + alpha * R)

    # ── compensator (integral of lambda from 0 to T) ──────────────────────────
    compensator = mu * T + (alpha / beta) * np.sum(
        1.0 - np.exp(-beta * (T - event_times))
    )

    return -(np.sum(log_terms) - compensator)


# ── MLE fitting ───────────────────────────────────────────────────────────────

def fit_hawkes(
    event_times: np.ndarray,
    T: float,
    n_restarts: int = 10,
    seed: int | None = None,
) -> HawkesFitResult:
    """
    Fit a Hawkes process to observed event times via MLE (Nelder-Mead).

    Multiple random restarts guard against local minima in the non-convex
    log-likelihood surface.

    Parameters
    ----------
    event_times : sorted array of event timestamps
    T           : length of the observation window (same units as event_times)
    n_restarts  : number of random starting points
    seed        : for reproducible starting points
    """
    rng = np.random.default_rng(seed)
    event_times = np.sort(event_times)

    best_result = None
    best_ll = np.inf

    for _ in range(n_restarts):
        x0 = [
            rng.uniform(0.1, 2.0),   # mu
            rng.uniform(0.1, 0.8),   # alpha
            rng.uniform(1.0, 5.0),   # beta
        ]
        res = minimize(
            hawkes_log_likelihood,
            x0,
            args=(event_times, T),
            method="Nelder-Mead",
            options={"xatol": 1e-6, "fatol": 1e-6, "maxiter": 5_000},
        )
        if res.fun < best_ll:
            best_ll = res.fun
            best_result = res

    mu, alpha, beta = best_result.x
    # Clip to valid range in case optimizer drifted slightly
    mu = max(mu, 1e-8)
    alpha = max(alpha, 1e-8)
    beta = max(beta, alpha + 1e-8)   # enforce stationarity

    return HawkesFitResult(
        params=HawkesParams(mu=mu, alpha=alpha, beta=beta),
        log_likelihood=-best_result.fun,
        n_events=len(event_times),
        T=T,
        converged=best_result.success,
    )


# ── simulation ────────────────────────────────────────────────────────────────

def simulate_hawkes(
    mu: float,
    alpha: float,
    beta: float,
    T: float,
    seed: int | None = None,
) -> np.ndarray:
    """
    Simulate a Hawkes process via Ogata's modified thinning algorithm.

    Time complexity: O(n) in the number of accepted events.

    Parameters
    ----------
    mu, alpha, beta : Hawkes parameters (stationarity: alpha < beta)
    T               : observation window length
    seed            : random seed

    Returns
    -------
    np.ndarray of event times in [0, T], sorted ascending.
    """
    if alpha >= beta:
        raise ValueError(
            f"Stationarity violated: alpha ({alpha}) must be < beta ({beta}). "
            f"Branching ratio = {alpha/beta:.3f} >= 1."
        )

    rng = np.random.default_rng(seed)
    times: list[float] = []
    t = 0.0
    R = 0.0            # running recursive sum  Sigma exp(-beta*(t - t_i))
    lambda_star = mu   # upper bound on intensity (tight after each event)

    while True:
        # Candidate inter-arrival time from the upper-bound Poisson process
        dt = rng.exponential(1.0 / lambda_star)
        t += dt
        if t > T:
            break

        # Decay R to the candidate time
        R *= np.exp(-beta * dt)

        # Actual intensity at the candidate time
        lambda_t = mu + alpha * R

        # Thinning: accept proportional to lambda_t / lambda_star
        if rng.uniform() < lambda_t / lambda_star:
            times.append(t)
            R += 1.0                        # new event's own contribution
            lambda_star = mu + alpha * R    # tight upper bound post-acceptance
        else:
            lambda_star = lambda_t          # lower bound after rejection

    return np.array(times)


# ── intensity curve (for plotting) ────────────────────────────────────────────

def compute_intensity(
    event_times: np.ndarray,
    params: HawkesParams,
    t_eval: np.ndarray,
) -> np.ndarray:
    """
    Evaluate lambda(t) at each point in t_eval.

    Uses vectorised numpy broadcasting: O(|t_eval| * |event_times|).
    Suitable for plotting with ~500 t_eval points and up to ~5,000 events.
    """
    # t_eval[:, None] - event_times[None, :] -> (n_eval, n_events) differences
    dt = t_eval[:, None] - event_times[None, :]   # shape (n_eval, n_events)
    # Only past events contribute
    mask = dt > 0
    contributions = np.where(mask, np.exp(-params.beta * dt), 0.0)
    return params.mu + params.alpha * contributions.sum(axis=1)


# ── rolling branching-ratio proxy ─────────────────────────────────────────────

def rolling_intensity(
    event_times: np.ndarray,
    params: HawkesParams,
    window: float,
    step: float | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Rolling mean intensity in windows of width `window`.

    Returns (t_centres, mean_intensities).
    """
    if step is None:
        step = window / 2.0
    t_start = event_times[0]
    t_end = event_times[-1]
    centres = np.arange(t_start + window / 2.0, t_end - window / 2.0, step)
    intensities = []
    for c in centres:
        lo, hi = c - window / 2.0, c + window / 2.0
        n = np.sum((event_times >= lo) & (event_times < hi))
        intensities.append(n / window)
    return centres, np.array(intensities)
